version: "3"

services:
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    restart: always
    volumes:
      - consul-data:/consul/data
    networks:
      apisix:

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    restart: always
    volumes:
    - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
    - "9000:9000"
    networks:
      apisix:

  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.6.0-debian}
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
      - consul
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.5.10
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

  web1:
    build:
      context: echo
    restart: always
    ports:
      - "9081:8088/tcp"
      - "9083:8089/tcp"
    depends_on:
      - consul
    environment:
      - HTTP_PORT=8088
      - GRPC_PORT=8089
      - VERSION=1
      - CONSUL_HTTP_ADDR=consul:8500
      - HEALTH_CHECK_INTERVAL=1s
      - DEREGISTER_CRITICAL_SERVICE_AFTER=10m
    networks:
      apisix:

  web2:
    build:
      context: echo
    restart: always
    ports:
      - "9082:8088/tcp"
      - "9084:8089/tcp"
    depends_on:
      - consul
    environment:
      - HTTP_PORT=8088
      - GRPC_PORT=8089
      - VERSION=2
      - CONSUL_HTTP_ADDR=consul:8500
      - HEALTH_CHECK_INTERVAL=1s
      - DEREGISTER_CRITICAL_SERVICE_AFTER=10m
    networks:
      apisix:

  prometheus:
    image: prom/prometheus:v2.25.0
    restart: always
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      apisix:

  grafana:
    image: grafana/grafana:7.3.7
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - "./grafana_conf/provisioning:/etc/grafana/provisioning"
      - "./grafana_conf/dashboards:/var/lib/grafana/dashboards"
      - "./grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
  consul-data: